cart/urls.py
from django.urls import path

from cart.views import cart_home, cart_update, checkout_home, checkout_done_view, cart_detail_api_view

app_name = "cart"

urlpatterns = [
    path('', cart_home, name='home'),
    path('api/', cart_detail_api_view, name='api'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success/', checkout_done_view, name='success'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from accounts.views import login_page, guest_register_view, register_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from django.conf import settings
from config.view import home_page
from django.conf.urls.static import static

urlpatterns = [
    path('', home_page, name='home'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('login/', login_page, name='login'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('register/', register_page, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/templates/carts/snippets/remove-product.html
<form class='form-product-ajax' method='POST' action='{% url "cart:update" %}' data-endpoint='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input class='cart-item-product-id' type='hidden' name='product_id' value='{{ product_id }}' />
    In cart <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Remove?</button>
    </span>
</form>